ASC.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASC.Web.Configuration;
using ASC.Web.DataModels;
using ASC.Web.Interfaces;
using ASC.Web.Models.BaseTypes;
using ASC.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace ASC.Web.Controllers
{
  public class DashboardController : BaseController
  {
    private readonly IOptions<ApplicationSettings> _settings;
    private readonly IServiceRequestOperations _operations;
    private readonly IMasterDataOperations _masterData;

    public DashboardController(IOptions<ApplicationSettings> settings, IServiceRequestOperations operations, IMasterDataOperations masterData)
    {
      _settings = settings;
      _operations = operations;
      _masterData = masterData;
    }

    public async Task<IActionResult> Dashboard()
    {

      var status = new List<string>
        {
          Status.New.ToString(),
          Status.InProgress.ToString(),
          Status.Initiated.ToString(),
          Status.RequestForInformation.ToString()

        };

      List<ServiceRequest> serviceRequests = new List<ServiceRequest>();

      if (HttpContext.User.IsInRole(Roles.Admin.ToString()))
      {
        serviceRequests =
          await _operations.GetServiceRequestsByRequestedDateAndStatus(DateTime.UtcNow.AddDays(-7), status);
      }

      else if (HttpContext.User.IsInRole(Roles.Engineer.ToString()))
      {
        serviceRequests =
          await _operations.GetServiceRequestsByRequestedDateAndStatus(DateTime.UtcNow.AddDays(-7), status,
            serviceEngineerEmail: HttpContext.User.Identity.Name);
      }

      else
      {
        serviceRequests =
          await _operations.GetServiceRequestsByRequestedDateAndStatus(DateTime.UtcNow.AddYears(-1),
            email: HttpContext.User.Identity.Name);
      }

      return View(new DashboardViewModel{ServiceRequests = serviceRequests.OrderByDescending(p=> p.RequestedDate).ToList()});
    }


  }
}

ASC.Web/Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASC.Web.DataModels;
using ASC.Web.Interfaces;
using ASC.Web.Models.ViewModels;
using ASC.Web.Utilities;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ASC.Web.Controllers
{
  [Authorize(Roles = "Admin")]
  public class MasterDataController : BaseController
  {
    private readonly IMasterDataOperations _masterData;
    private readonly IMapper _mapper;

    public MasterDataController(IMasterDataOperations masterData, IMapper mapper)
    {
      _masterData = masterData;
      _mapper = mapper;
    }

    [HttpGet]
    public async Task<IActionResult> MasterKeys()
    {
      var masterKeys = await _masterData.GetAllMasterKeysAsync();
      var masterKeysViewModel = _mapper.Map<List<MasterDataKey>, List<MasterDataKeyViewModel>>(masterKeys);

      // Hold all Master Keys in session
      HttpContext.Session.SetSession("MasterKeys", masterKeysViewModel);

      return View(new MasterKeysViewModel
      {
        MasterKeys = masterKeysViewModel == null ? null : masterKeysViewModel.ToList(),
        IsEdit = false
      });

    }

    [HttpGet]
    public async Task<IActionResult> MasterValues()
    {
      // Get All Master Keys and hold them in ViewBag for Select tag
      var masterKeys = await _masterData.GetAllMasterKeysAsync();
      ViewBag.MasterKeys = masterKeys;
      return View(new MasterValuesViewModel
      {
        MasterValues = new List<MasterDataValueViewModel>(),
        IsEdit = false
      });
    }

    [HttpGet]
    public async Task<IActionResult> MasterValuesByKey(Guid key)
    {
      // Get Master values based on master key.
      var data = await _masterData.GetAllMasterValuesByKeyAsync(key);
      return Json(new { data = data });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> MasterValues(bool isEdit, MasterDataValueViewModel
      masterValue)
    {
      if (!ModelState.IsValid)
      {
        return Json("Error");
      }
      var masterDataValue = _mapper.Map<MasterDataValueViewModel,
        MasterDataValue>(masterValue);
      if (isEdit)
      {
        // Update Master Value
        await _masterData.UpdateMasterValueAsync(masterDataValue);
      }
      else
      {
        // Insert Master Value
        await _masterData.InsertMasterValueAsync(masterDataValue);
      }
      return Json(true);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> MasterKeys(MasterKeysViewModel masterKeys)
    {
      masterKeys.MasterKeys = HttpContext.Session.GetSession<List<MasterDataKeyViewModel>>("MasterKeys");
      if (!ModelState.IsValid)
      {
        return View(masterKeys);
      }
      var masterKey = _mapper.Map<MasterDataKeyViewModel, MasterDataKey>(masterKeys.
        MasterKeyInContext);
      if (masterKeys.IsEdit)
      {
        // Update Master Key
        await _masterData.UpdateMasterKeyAsync(masterKey);
      }
      else
      {
        // Insert Master Key
        await _masterData.InsertMasterKeyAsync(masterKey);
      }
      return RedirectToAction("MasterKeys");
    }
  }
}

ASC.Web/Views/Shared/AccessDenied.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor UserHttpContext
@{
  ViewData["Title"] = "Error";
  Layout = !UserHttpContext.HttpContext.User.Identity.IsAuthenticated ? "_layout" : "_SecureLayout";
}
<div class="row">
  <div class="col s12">
    <div class="card-panel orange lighten-1 margin-bottom-50px margin-top-50px">
      <span class="white-text">
        Access Denied.
      </span>
    </div>
  </div>
</div>

ASC.Web/Views/Shared/CustomError.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor UserHttpContext
@{
  ViewData["Title"] = "Error";
  Layout = !UserHttpContext.HttpContext.User.Identity.IsAuthenticated ? "_layout" : "_SecureLayout";
}

<div class="row">
  <div class="col s12">
    <div class="card-panel orange lighten-1 margin-bottom-50px margin-top-50px">
      <span class="white-text">
        An error occurred while processing your request. Please contact customer
        service with following
        Ticket No. @ViewData["ExceptionId"]
      </span>
    </div>
  </div>
</div>

ASC.Web/Views/Shared/NotFound.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor UserHttpContext
@{
  ViewData["Title"] = "Error";
  Layout = !UserHttpContext.HttpContext.User.Identity.IsAuthenticated ? "_layout" :
    "_SecureLayout";
}
<div class="row">
<div class="col s12">
<div class="card-panel orange lighten-1 margin-bottom-50px margin-top-50px">
<span class="white-text">
        Page not found.
      </span>
    </div>
  </div>
</div>

ASC.Web/Views/Shared/ServiceRequestGrid.cshtml
@using ASC.Web.Models.BaseTypes
@model IEnumerable<ASC.Web.DataModels.ServiceRequest>
@{
  var isAudit = ViewBag.IsAudit;
}

<div class="row"></div>
<div class="row padding-top-20px">
<div class="row z-depth-3">
  <div class="section white-text padding-left-10px blue-grey lighten-1">
    <h5>@ViewBag.SectionName</h5>
  </div>
  <div class="divider"></div>
<div class="col s12 padding-bottom-15px">
  @* Display List of Service Requests *@
  <table class="highlight centered tblServiceRequests" id="@ViewBag.Id">
  <thead>
  <tr>
  <th data-field="RowKey">RowKey</th>
  <th data-field="PartitionKey">User</th>
  <th data-field="Status">Status</th>
  <th data-field="RequestedDate">Requested Date</th>
  <th data-field="ServiceEngineer">Service Engineer</th>
  <th data-field="Actions">View</th>
</tr>
</thead>
<tbody>
@foreach (var serviceRequest in Model)
{
  <tr>
  <td>@serviceRequest.Id</td>
  <td>@serviceRequest.Customer</td>
  <td>
    @switch ((Status)Enum.Parse(typeof(Status), serviceRequest.
      Status))
    {
      case Status.New:
      case Status.Initiated:
      case Status.InProgress:
      case Status.Completed:
        <div class="white-text teal lighten-1 center-align">
          <span>@serviceRequest.Status</span>
        </div>
        break;
      case Status.RequestForInformation:
      case Status.Pending:
      case Status.Denied:
        <div class="white-text red lighten-1 center-align">
          <span>@serviceRequest.Status</span>
        </div>
        break;
      case Status.PendingCustomerApproval:
        <div class="white-text orange lighten-1 center-align">
          <span>@serviceRequest.Status</span>
        </div>
        break;
      default:
        break;
    }
  </td>
    <td>@(serviceRequest.RequestedDate == null ? "" : serviceRequest.
            RequestedDate.Value.ToString("dd/MM/yyyy") )</td>
    <td>@serviceRequest.ServiceEngineer</td>
    <td><i class="small material-icons view cursor-hand">pageview</i></td>
  </tr>
}
    </tbody>
    </table>
  </div>
</div>
</div>

ASC.Web/Views/Shared/_Layout.cshtml
@{ 
    Layout = "_MasterLayout";
}
<header>
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="/" class="brand-logo">
                <img class="responsive-img" src="~/images/logo.jpg" alt="Logo" />
            </a>
            <ul class="right hide-on-med-and-down">
                <li><a href="/Account/Login">Login</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <ul id="nav-mobile" class="side-nav">
                <li><a href="/Account/Login">Login</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
            <div class="container">
                <br><br>
                <h1 class="header center teal-text text-lighten-2">Automobile Service Center</h1>
                <div class="row center">
                    <h5 class="header col s12 light ">Where Quality meets Safety</h5>
                </div>
                <div class="row center">
                    <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
                </div>
                <br><br>
            </div>
        </div>
        <div class="parallax"><img src="~/images/background1.jpg" alt="Unsplashed background img 1"></div>
    </div>
</header>

<!-- Render Body -->
<main>
    <div class="row margin-bottom-0px">
        <div class="col s12 padding-0px">
            @RenderBody()
        </div>
    </div>
</main>

<!-- Footer -->
<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">About Us</h5>
                <p class="grey-text text-lighten-4">
                    Automobile Service Center is certified Company to perform car services. Our Workshop operations started in the month of October, 2010.
                    We primarily focus on providing better services to our customers, and as a result of the hard work we were awarded as the "Best Service" for the year 2008 and that too within a short period of time.
                </p>

            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Additional Services</h5>
                <ul>
                    <li><a class="white-text" href="#!">Services</a></li>
                    <li><a class="white-text" href="#!">Finance</a></li>
                    <li><a class="white-text" href="#!">Used Cars</a></li>
                    <li><a class="white-text" href="#!">Insurance</a></li>
                    <li><a class="white-text" href="#!">Driving School</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#!">Facebook</a></li>
                    <li><a class="white-text" href="#!">LinkedIn</a></li>
                    <li><a class="white-text" href="#!">Twitter</a></li>
                    <li><a class="white-text" href="#!">Youtube</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Powered by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>

@section Scripts{
  @RenderSection("Scripts", required: false)
}

ASC.Web/Views/Shared/_MasterLayout.cshtml
@using Microsoft.Extensions.Options;
@using ASC.Web.Configuration;
@using Microsoft.AspNetCore.Http
@inject IOptions<ApplicationSettings> _configurationSettings




<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" />
  <title>@_configurationSettings.Value.ApplicationTitle</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" media="screen,projection" />
  <link href="~/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
  <link href="~/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />

</head>
<body>
  <!-- Render Body -->
  @RenderBody()

  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
  <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/js/materialize.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
  <script src="~/js/init.js"></script>

  @RenderSection("Scripts", required: false)
</body>
</html>

ASC.Web/Views/Shared/_SecureLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor UserHttpContext
@{
  Layout = "_MasterLayout";
  var currentUserName = UserHttpContext.HttpContext.User.Identity.Name;
}

<!-- Header -->
<header class="secureLayout">
  <nav class="top-nav blue-grey lighten-1">
    <div class="nav-wrapper row valign-wrapper">
      <div class="col s12 valign-wrapper">
        <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only white-text"><i class="material-icons">menu</i></a>
        <h5><a class="page-title">Automobile Service Center</a></h5>
      </div>
    </div>
  </nav>

  <!-- Side NavBar -->
  <ul id="nav-mobile" class="side-nav fixed">
    <li>
      <div class="userView">
        <div class="background blue-grey lighten-1"></div>
        <a href="#!user"><img class="circle" src="~/images/male.png"></a>
        <a href="#!name"><p class="white-text name">Username:<br />@currentUserName</p></a>
        @if (User.IsInRole("Admin"))
        {
          <a href="#!name"><span class="white-text name">Role:<br /> Admin</span></a>
        }
        else if (User.IsInRole("Engineer"))
        {
          <a href="#!name"><p class="white-text name">Role:<br /> Engineer</p></a>
        }
        else
        {
          <a href="#!name"><p class="white-text name">Role:<br /> User</p></a>
        }
      </div>
    </li>
    <li><a class="collapsible-header" asp-controller="Dashboard" asp-action="Dashboard"><i class="material-icons">dashboard</i>Dashboard</a></li>

    <li>
      <ul class="collapsible collapsible-accordion">
        <li>
          <a class="collapsible-header">User Administration<i class="material-icons">supervisor_account</i></a>
          <div class="collapsible-body">
            <ul>
              <li><a asp-controller="Account" asp-action="Customers">Customers<i class="material-icons">account_box</i>
              </a></li>
              <li><a href="#!">Deactivate Customer<i class="material-icons">remove_circle</i></a></li>
              <li><a asp-controller="Account" asp-action="ServiceEngineers">Service Engineers<i class="material-icons">person_add</i></a></li>
            </ul>
          </div>
        </li>
      </ul>
    </li>
    <li>
      <ul class="collapsible collapsible-accordion">
        <li>
          <a class="collapsible-header">Master Data<i class="material-icons">
            perm_data_setting</i></a>
          <div class="collapsible-body">
            <ul>
              <li><a asp-controller="MasterData" asp-action="MasterKeys"
                     class="collapsible-header">Master Keys<i class="material-icons">data_
                usage</i></a></li>
              <li><a class="collapsible-header" asp-controller="MasterData" asp-action="MasterValues"
                     id="ancrResetPassword">Master Values<i class="material-icons">settings_
                system_daydream</i></a></li>
            </ul>
          </div>
        </li>
      </ul>
    </li>
    <li><a class="collapsible-header" asp-controller="ServiceRequest" asp-action="ServiceRequest"><i class="material-icons">perm_data_setting</i>Service Requests</a></li>
    <li><a class="collapsible-header" href="#!"><i class="material-icons">inbox</i>Promotions</a></li>
    <li><a class="collapsible-header" href="#!"><i class="material-icons">settings</i>Settings</a></li>
    <li>
    <li>
      <ul class="collapsible collapsible-accordion">
        <li>
          <a class="collapsible-header">
            <i class="materialicons">
              settings
            </i>
          </a>
          <div class="collapsible-body">
            <ul>
              <li>
                <a class="collapsible-header" href="#!" id="ancrResetPassword">
                  Reset Password<i class="material-icons">lock_outline</i>
                </a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </li>
    </li>
    <li><a class="collapsible-header" id="ancrLogout" href="#!"><i class="material-icons">exit_to_app</i>Logout</a></li>
  </ul>
</header>

<!-- Render Body -->
<main class="secureLayout">
  <div class="row margin-bottom-0px">
    <div class="col s12">
      @RenderBody()
    </div>
  </div>
</main>

<!-- Footer -->
<footer class="page-footer blue-grey lighten-1 secureLayout">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">About Us</h5>
      <p class="grey-text text-lighten-4">
        Automobile Service Center is certified Company to perform car services. Our Workshop operations started in the month of October, 2010.
        We primarily focus on providing better services to our customers, and as a result of the hard work we were awarded as the "Best Service" for the year 2008 and that too within a short period of time.
      </p>

    </div>
    <div class="col l3 s12">
      <h5 class="white-text">Additional Services</h5>
      <ul>
        <li><a class="white-text" href="#!">Services</a></li>
        <li><a class="white-text" href="#!">Finance</a></li>
        <li><a class="white-text" href="#!">Used Cars</a></li>
        <li><a class="white-text" href="#!">Insurance</a></li>
        <li><a class="white-text" href="#!">Driving School</a></li>
      </ul>
    </div>
    <div class="col l3 s12">
      <h5 class="white-text">Connect</h5>
      <ul>
        <li><a class="white-text" href="#!">Facebook</a></li>
        <li><a class="white-text" href="#!">LinkedIn</a></li>
        <li><a class="white-text" href="#!">Twitter</a></li>
        <li><a class="white-text" href="#!">Youtube</a></li>
      </ul>
    </div>
  </div>
  <div class="footer-copyright row margin-bottom-0px">
    <div class="col s12">
      Powered by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
    </div>
  </div>
</footer>
<!-- Hidden Forms -->
<form class="hide" method="post" id="logout_form" asp-controller="Account" asp-action="Logout">
  <input type="submit" value="Logout" />
</form>
<form class="hide" method="post" id="resetPassword_form" asp-controller="Account" asp-action="InitiateResetPassword" asp-route-email="@currentUserName"></form>
<!-- End Hidden Forms -->
@section Scripts{
  @RenderSection("Scripts", required: false)


  <script type="text/javascript">
    $(function () {
      $('#ancrLogout').click(function () {
        $('#logout_form').submit();
      });

      $('#ancrResetPassword').click(function () {
        $('#resetPassword_form').submit();
      });


    })
  </script>
}